# Generated by Django 6.0.3 on 2026-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('fv_simple', models.FloatField(default=0.0)),
                ('fv_dcf', models.FloatField(default=0.0)),
                ('fv_avg', models.FloatField(default=0.0)),
                ('margin', models.FloatField(default=0.0)),
                ('roe', models.FloatField(default=0.0)),
                ('debt_fcf', models.FloatField(default=0.0)),
                ('fcf', models.FloatField(default=0.0)),
                ('growth', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
