# Generated by Django 6.0.3 on 2026-03-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='strategy',
            field=models.CharField(choices=[('trading', 'Trading'), ('long_term', 'Cartera/Largo Plazo')], default='trading', max_length=20),
        ),
    ]
