# Generated by Django 6.0.3 on 2026-03-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stock_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='debt_fcf',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fcf',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='growth',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='roe',
        ),
    ]
