# Generated by Django 6.0.3 on 2026-03-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_stock_debt_fcf_remove_stock_fcf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='strategy',
            field=models.CharField(choices=[('trading', 'Trading'), ('long_term', 'Cartera')], default='trading', max_length=20),
        ),
    ]
