# Generated by Django 6.0.3 on 2026-03-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_stock_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='alert_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='trade_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='trade_status',
            field=models.CharField(choices=[('none', 'Nada'), ('buy', 'Comprado (Long)'), ('sell', 'Vendido (Short)')], default='none', max_length=10),
        ),
    ]
