# Generated by Django 6.0.3 on 2026-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_stock_alert_price_stock_analyzed_stock_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='trade_status',
            field=models.CharField(choices=[('none', 'Esperar'), ('buy', 'Comprado (Long)'), ('sell', 'Vendido (Short)')], default='none', max_length=10),
        ),
    ]
