# Generated by Django 6.0.3 on 2026-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_stock_trade_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='notes',
            new_name='Observaciones',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fv_avg',
            new_name='fv',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='alert_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fv_dcf',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fv_simple',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='trade_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='stock',
            name='strategy',
            field=models.CharField(choices=[('xt', 'XTB'), ('bm', 'B M'), ('qu', 'Quant')], default='trading', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trade_status',
            field=models.CharField(choices=[('none', 'Esperar'), ('buy', 'Comprado'), ('sell', 'Vendido')], default='none', max_length=10),
        ),
    ]
