# Generated by Django 6.0.3 on 2026-03-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_notes_stock_observaciones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='analyzed',
            new_name='bmt',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='strategy',
        ),
        migrations.AddField(
            model_name='stock',
            name='qut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='xtb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='trade_status',
            field=models.CharField(choices=[('0', 'EVALUAR'), ('1', 'OPERATIVA'), ('2', 'INACTIVA')], default='0', max_length=10),
        ),
    ]
