# Generated by Django 6.0.3 on 2026-03-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_analyzed_stock_bmt_remove_stock_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fecha_inactivacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha para evaluar'),
        ),
    ]
