# Generated by Django 6.0.3 on 2026-03-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_stock_fecha_inactivacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la empresa'),
        ),
    ]
