# Generated by Django 6.0.3 on 2026-03-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_stock_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='trade_status',
            field=models.CharField(choices=[('0', 'EVALUAR'), ('1', 'OPERATIVA'), ('2', 'INACTIVA'), ('3', 'NUEVA'), ('sell', 'VENTA')], default='0', max_length=10),
        ),
    ]
