# Generated by Django 6.0.3 on 2026-03-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_stock_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='long_profit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Long Take Profit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='long_stop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Long Stop Loss'),
        ),
        migrations.AddField(
            model_name='stock',
            name='ref_long',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Long'),
        ),
        migrations.AddField(
            model_name='stock',
            name='ref_short',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Short'),
        ),
        migrations.AddField(
            model_name='stock',
            name='short_profit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Take Profit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='short_stop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Stop Loss'),
        ),
    ]
