# Generated by Django 6.0.3 on 2026-03-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_stock_long_profit_stock_long_stop_stock_ref_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='trade_status',
            field=models.CharField(choices=[('0', 'SEGUIR'), ('1', 'OPERATIVA'), ('2', 'INACTIVA'), ('3', 'NUEVA'), ('sell', 'VENTA')], default='0', max_length=10),
        ),
    ]
